apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T09:49:36Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "3858"
  uid: e3466d65-f3af-49d6-8366-04132c1a2cc6
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.102.7.119
  clusterIPs:
  - 10.102.7.119
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31643
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
